// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0UZIF6jJuUeqQyiaRltpUz-7b12TgpE',
    appId: '1:348688129087:web:c900a2e8df314b1bdeec8a',
    messagingSenderId: '348688129087',
    projectId: 'bloc-photo-library-94713',
    authDomain: 'bloc-photo-library-94713.firebaseapp.com',
    storageBucket: 'bloc-photo-library-94713.appspot.com',
    measurementId: 'G-XEN6G5L6WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDns4RTzetSQzmj9nQwdlGU6aUpSjg710E',
    appId: '1:348688129087:android:f6be4ecf51295783deec8a',
    messagingSenderId: '348688129087',
    projectId: 'bloc-photo-library-94713',
    storageBucket: 'bloc-photo-library-94713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBm-PzefHK3Wno-V4-w-pSsCZybwhvkLI',
    appId: '1:348688129087:ios:afe7c48fd373ee8adeec8a',
    messagingSenderId: '348688129087',
    projectId: 'bloc-photo-library-94713',
    storageBucket: 'bloc-photo-library-94713.appspot.com',
    iosBundleId: 'com.example.blocPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBm-PzefHK3Wno-V4-w-pSsCZybwhvkLI',
    appId: '1:348688129087:ios:afe7c48fd373ee8adeec8a',
    messagingSenderId: '348688129087',
    projectId: 'bloc-photo-library-94713',
    storageBucket: 'bloc-photo-library-94713.appspot.com',
    iosBundleId: 'com.example.blocPractice',
  );
}
